name: Test matrix
on: workflow_dispatch
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        build_type: [Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install doxygen
      run: sudo apt-get install doxygen
    - name: install graphviz dot
      run: sudo apt install graphviz
    - name: Build folder
      run: mkdir build
    - name: CMake
      run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Make
      run: cd build && make -j4
    - name: Tests
      run: cd build && ctest
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - name: Deploy
      run: |
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/beacon/beacon gs://marlin-artifacts/bin/beacon_${{ matrix.os }}_${{ matrix.build_type }}
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/relay/eth_relay gs://marlin-artifacts/bin/eth_relay_${{ matrix.os }}_${{ matrix.build_type }}
       gsutil -h "Cache-Control:no-cache, max-age=0" cp build/integrations/eth/onramp_eth gs://marlin-artifacts/bin/onramp_eth_${{ matrix.os }}_${{ matrix.build_type }}
